### PR TITLE
Add Hooks in Bricks Starter

### PR DESCRIPTION
**Pull request by Prashant4900**

### CODE REVIEW

**Comment by Prn-Ice** [comment]
Looks good, what do hooks do, I saw them in some other examples but since you brought it up could I just learn from you 😃?

**Comment by Prashant4900** [comment]
Hooks provide additional scripts like if you want to run a command like pub add bloc you can write it on pre_gen.dart file and after brick generate you can rum pub get in post_gen.dart.

**Comment by Prn-Ice** [comment]
Sorry for the delay, really nice updates, I'm currently on holiday, no laptop, I'll merge and publish in a few days.

**Comment by Prashant4900** [comment]
Okay no problem

**Review by Prn-Ice — COMMENTED** [review]
Why do we need [this](https://github.com/Prn-Ice/mason_bricks/pull/1/files/2827f209acc01bf5b076d704c66491c830c7fff4#diff-b20b9cd78d0a3ad3dab4d1a69de6252ecab9ed134ead1106e2a30eee7688dee5)?

**Comment by Prashant4900** [comment]
it's just a sample code.

**Pull request merged**
